spring:
  main:
    log-startup-info: true # выводим служебную информацию
    banner-mode: off       # не выводим баннер
  config:
    import: "classpath:quiz/questions.yaml"


logging.level:
  # root: TRACE
  # ru.yandex.practicum.quiz.QuizApp: WARN # настраиваем уровень логера
  ru.yandex.practicum.quiz: TRACE

spring-quiz:
  report:
    mode: "concise"  # краткий режим отчёта